---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tulliocba/config-repository
server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh